### ISSUE TITLE
Declaring, modifying, and using class fields

### ISSUE THREAD

**Issue by Artyom-IWT** [resess/Slicer4J#10]
`Issue.java`:
```java
1.  import java.util.ArrayList;
2.  import java.util.List;
3.  
4.  public class Issue {
5.  
6.      static List<String> list = new ArrayList<>();
7.  
8.      public static void main(String[] args) {
9.          list.add("A");
10.         System.out.println(list.get(0));
11.     }
12. }
```

Running Slicer4J w.r.t. `Issue:10` line:
```bash
python3 slicer4j.py -j .../issue.jar -o .../issue -b Issue:10 -m "Issue"
```

`slice.log`:
```
Issue:10
Issue:6
```

As you can see, the statement `list.add("A")` on the 9th line wasn't included in the slice. 
Note: if the variable `list` was declared inside the method body, the statement `list.add("A")` would be included in the slice.

**Comment by khaled-e-a** [comment]
fixed in latest DynamicSlicingCore and Slicer4J and added tests.
