### ISSUE TITLE
Missing .gitmodules file

### ISSUE THREAD

**Issue by david-fong** [resess/Slicer4J#13]
It seems that the root .gitmodules file wasn't committed to the repo. This problem prevents users of this repo from running the defects4j benchmarks.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by khaled-e-a** [comment]
Pushed the Defects4J files. Thanks for bringing this to my attention!

**Comment by david-fong** [comment]
Thanks. I see you pasted the repos in. The git submodule route seems cleaner (easier to update and doesn't bloat the repo) but this works.

I think you missed copying the LICENSE file for the jackson-core repos. I think you need to do that to fulfill the Apache license section 4a. Can you check?
