### ISSUE TITLE
 Could not find or load main class SliceMe,  MavenReportException: Error while generating Javadoc.

### ISSUE THREAD

**Issue by Ghadalamer** [resess/Slicer4J#26]
i'm trying to execute the SliceMe example but i'm facing some issues. i made sure that the files structure is as instructed, but when i run the python command i get these errors:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/94056305/195354179-ccb677e7-847e-4dfc-add4-990c4fb9e2a7.png">

when i ran mvn -Dmaven.test.skip=true clean install to the Slicer4J i got this error:
<img width="853" alt="javadocErrors" src="https://user-images.githubusercontent.com/94056305/195354781-2752dbdb-1afb-4e26-bf6f-0fc64c8027a0.png">
even though it has built successfully, it might be the cause but i couldn't figure how to fix it. 
java version 1.8, python 3.
any help?

**Comment by khaled-e-a** [comment]
The problem seems to be due to the path of Slicer4J which contains non-English letters and spaces (which later shows as ???..). Please re-install the tool in a path that doesn't have these issues and try again.

**Comment by Ghadalamer** [comment]
it worked! may Allah bless you, thank you for the quick response!
