### ISSUE TITLE
Analyze .jar file that does not contain line number 

### ISSUE THREAD

**Issue by itstartstosnow** [resess/Slicer4J#30]
Hi, 

I am trying to analyze a `.jar` file that do not contain the line number information, therefore failing to provide the parameter. (I tried `javap -l` and `javap -v` and there is no line number table. )

I don't have the source code, and it seems that the debug symbols were not included when it was compiled. Any suggestion on how to deal with this case? Thanks!

**Comment by mmoschenskikh** [comment]
> Any suggestion on how to deal with this case?

Hi, @itstartstosnow !

The suggestion I have is to insert line numbers into the bytecode, for example, using ASM library.
[Here](https://www.beyondjava.net/quick-guide-writing-byte-code-asm) I found an article that gives an example how to achieve this.

**Comment by itstartstosnow** [comment]
> I don't understand what's the purpose of slicing a program when you don't have its source code.
> 
> Anyway, I have two ideas that might help you.
> 
> * Insert line numbers into the bytecode, for example, using [ASM library](https://asm.ow2.io/).
>   [Here I found an article](https://www.beyondjava.net/quick-guide-writing-byte-code-asm) that gives an example how to achieve this.
> * Decompile your `.jar`, for example, using [JD-GUI decompiler](https://github.com/java-decompiler/jd-gui). Then you can assemble it back manually or using build systems like Maven or Gradle (most likely, you'll have to do some setup before you can finally bring it back).

Thanks for your answer! Perhaps I am in a wrong direction. I was doing reverse engineering, and maybe I should find another method to do it. 

Thanks for the sources, and I guess I should use the decompiler to manually do the work!

**Comment by khaled-e-a** [comment]
Hi @itstartstosnow and @mmoschenskikh , thank you both for your interest in Slicer4J!

You can still use the tool even if the jar has no line numbers, but in that case you need to slice from a trace statement. The -sp parameter for [this line](https://github.com/resess/Slicer4J/blob/8389bc48d708923e4a8a3ca14d06d8acb5db2a2b/scripts/slicer4j.py#LL131C1-L131C1) is the trace statement number, You can modify the slicer4j.py such that after the trace is collected, you can inspect the trace, select a trace statement to slice from, then pass that trace statement number to the slicing command by -sp. 

slicer4j.py is just a wrapper script around Slicer4J APIs that it 1- instruments the jar, 2- runs the jar to collect a trace, 3- takes a jar line number to slice from, 4- figures out which statements in the trace correspond to that jar line, then 5- slices from that trace statements. So you can skip 3 and 4 if you don't have line numbers in the jar and just slice from trace statement. 

Hope this helps!
