### ISSUE TITLE
Error: Could not find or load main class SliceMe

### ISSUE THREAD

**Issue by da-123-snake** [resess/Slicer4J#36]
I meet a iuuse:

(deepseek) cmd@zkti:/data/cmd/slice/DynamicSlicingCore/Slicer4J/scripts$ python3 slicer4j.py -j ../benchmarks/SliceMe/target/SliceMe-1.0.0.jar -o sliceme_slice/ -b SliceMe:8 -m "SliceMe"
Instrumenting the JAR
Instrumented jar is at: /data/cmd/slice/DynamicSlicingCore/Slicer4J/scripts/sliceme_slice/SliceMe-1.0.0_i.jar
Running the instrumented JAR
Running instrumented JAR
------------------------------------
Error: Could not find or load main class SliceMe
------------------------------------
Slicing from line SliceMe:8
Slice source code lines: /data/cmd/slice/DynamicSlicingCore/Slicer4J/scripts/sliceme_slice/slice.log
Raw slice: /data/cmd/slice/DynamicSlicingCore/Slicer4J/scripts/sliceme_slice/raw-slice.log
Slice graph: /data/cmd/slice/DynamicSlicingCore/Slicer4J/scripts/sliceme_slice/slice-graph.pdf
Slice with dependencies: /data/cmd/slice/DynamicSlicingCore/Slicer4J/scripts/sliceme_slice/slice-dependencies.log

**Comment by khaled-e-a** [comment]
There's no line 8 to slice from in SliceMe, it's not a real statement, line 8 is a curly bracket "}". please follow the Readme which indicates to slice from line 9.

Here's a demo of this command working.

![Screenshot 2024-11-18 at 9 08 02 PM](https://github.com/user-attachments/assets/bcde2199-16d9-451c-9c53-d4ac0eb785b3)

Please also check the logs in the output folder (sliceme_slice) to identify possible reasons why the command doesn't work for you.

Will close this issue untill further information is provided on why it fails on your side .
