### ISSUE TITLE
How do I run other projects without a pom.xml file in Defects4J?

### ISSUE THREAD

**Issue by da-123-snake** [resess/Slicer4J#37]
How do I run other projects without a pom.xml file in Defects4J?

**Comment by khaled-e-a** [comment]
Hi @da-123-snake 

Thank you for using Slicer4J.

To run Slicer4J, all you need is a compiled Jar and the path to its dependencies, as outlined in the ReadMe. 
To run any project in Defects4J, you just need to compile it first, then run Slicer4J on the compiled Jar. 

Please refer to Defects4J's instructions on how compile each specific benchmark.
