### ISSUE TITLE
Error：Could not find or load main class SliceMe

### ISSUE THREAD

**Issue by Seanmc1005** [resess/Slicer4J#38]
Hello, resess，

I'm sorry to bother you. Adding the newly submitted code seems to be problematic. The SliceMe project, which originally packaged slices normally under mvn 3.8 and jdk 8, now packages &&slices for the newly submitted code under the same environment, and an Error will be reported: Could not find or load main class SliceMe . After comparison, I found that you changed <source> and <target> in the pom file of SliceMe project in your submission, changing them from the original 1.6 to 1.7. Here I would like to ask whether the change will cause the use of Slicer4J this tool environment changes (sdk, maven)? Hope to get your reply, thank you, wish you a smooth scientific research.

best wishes!

**Comment by Seanmc1005** [comment]
![no mainclass](https://github.com/user-attachments/assets/cb77e4cd-e13c-446a-8e68-271c478f3ab3)

**Comment by khaled-e-a** [comment]
Hi @Seanmc1005 

Thank you for using Slicer4J.

The change in the pom file of benchmarks does not affect the tool. This change is done to support most users who cannot compile the legacy 1.6 code.
You can change the pom file's version of benchmarks back to 1.6 to fit your environment. But no changes were made to Slicer4J's required environment that is specified in the ReadMe. 

Please re-open this issue if you still cannot run the tool. Thank you.
