### ISSUE TITLE
Soot-Infoflow library

### ISSUE THREAD

**Issue by Lms24** [resess/Slicer4J#8]
Hello again,

after getting SLicer4J to run, I started looking into the source code and the dependencies. I noticed that Slicer4J's `pom.xml` declares `soot-infoflow` as a dependency with a local jar. I assume that was because by the time of developing the tool version 2.9 of the library was not yet released. According to [Maven Central](https://mvnrepository.com/artifact/de.tud.sse/soot-infoflow/2.9.0) version 2.9.0 is publicly available, removing the necessity of including the snapshot jar in this repository in the `libs` directory. I edited the `pom.xml` locally and it seems that everything works as before.  

If you want I can submit a PR with the updated `pom.xml` (although the change is quite subtle).

Have a good day!

**Comment by khaled-e-a** [comment]
Please submit a PR. Thank you!

**Comment by Lms24** [comment]
I'm sorry but I made a mistake when making the changes locally. Turns out that the Unit tests fail when exchanging the jar with the Maven Central one. So I won't submit a PR for it in the foreseeable future, sorry.
